spring:
  config:
    activate:
      on-profile: local
  application:
    name: apigateway-service
  cloud:
    discovery:
      client:
        service-id: ${spring.application.name}
    gateway:
      # default filter는 모든 라우터에 실행되는거. 그렇기에 현재는 필요없고 나중에 사용할 예정
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway GlobalFilter
#            preLogger: true
#            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
#            - AuthorizationHeaderFilter
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/game-service/**
          filters:
            - RewritePath=/game-service/(?<segment>.*),/$\{segment}
        - id: dis-game-service-1
          uri: lb://DIS-GAME-SERVICE-1
          predicates:
            - Path=/dis-game-service-1/**
          filters:
            - RewritePath=/dis-game-service-1/(?<segment>.*),/$\{segment}
        - id: dis-game-service-2
          uri: lb://DIS-GAME-SERVICE-2
          predicates:
            - Path=/dis-game-service-2/**
          filters:
            - RewritePath=/dis-game-service-2/(?<segment>.*),/$\{segment}
        - id: dis-game-service-3
          uri: lb://DIS-GAME-SERVICE-3
          predicates:
            - Path=/dis-game-service-3/**
          filters:
            - RewritePath=/dis-game-service-3/(?<segment>.*),/$\{segment}
    config:
      enabled: false

server:
  port: 9000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port}

token:
  secret: Y2hvcHBhLWRvbnQtYml0ZS1tZS1zcHJpbmctYm9vdC1qd3QtdGVzdC1zZWNyZXQta2V5LWNob3BwYS1kb250LWJpdGUtbWUtc3ByaW5nLWJvb3Qtand0LXRlc3Qtc2VjcmV0LWtleQo=